### ISSUE TITLE
Create real USB MIDI firmware

### ISSUE THREAD

**Issue by rogierhofboer** [WootingKb/wooting-analog-midi#3]
Not an issue, but just a wild idea I'd like to share.

Another way to do this without the need of an extra application, is to make the Wooting (also) a real USB MIDI device by creating special firmware.

See: 
https://www.usb.org/sites/default/files/midi10.pdf

and the more recent MIDI 2.0 standard:
https://www.usb.org/sites/default/files/USB%20MIDI%20v2_0.pdf

I am not sure if this is technically possible with the components used on the Wooting keyboards, maybe a standard USB HID 
controller, like the FTDI FT260 is used, in that case, this will not be possible.

**Comment by PastaJ36** [comment]
That would be pretty cool yeah. One issue I can foresee is that for MIDI you'll probably want to have very fine control over mapping, velocity etc, and that is much harder to control on the firmware than with the app like it is at the moment. On the other hand it would be pretty sweet to just have a plug and play MIDI device.

If it turns out there's a big interest we could look at it again, especially if we ever do any kind of macropad devices.

**Comment by rogierhofboer** [comment]
You could create a companion app for this, which configures settings in the firmware.

Just to be sure: I am just sharing technical idea's, not saying this solution is better or should be made at all ;)
