### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by Beeque** [WootingKb/wooting-analog-midi#7]
I'm unable to launch this software due to "Fatal error occured on initialisation" message with window title "INVALID TITLE WITH QUOTES"

Windows 10 Enterprise Version 21H1 (OS Build 19043.1110)

**Comment by simon-wh** [comment]
Hi, thanks for the report, the error window you got is quite confusing given the title, but I think I may have found the source. There's a good chance that it's caused by the Analog SDK not being installed, I'll have to do a bit more digging as to why it gives such an unhelpful message, but if you follow the Analog SDK install guide [here](https://github.com/WootingKb/wooting-analog-sdk#installing) it should hopefully get you going

EDIT: Found the reason why the error message is so unhelpful, it looks like the api changed recently for the dialogs, swapping around the title and message parameters as well as not supporting quotes, hence the invalid title message

**Comment by Beeque** [comment]
Hi, thanks for the reply, and for the solution! I did not have SDK installed, and now it works wonders (=

**Comment by simon-wh** [comment]
@Beeque Great to hear! Next update I push out will have a fixed error dialog so hopefully no-one else will run into that issue :)
